Controllers/KeywordsDepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication5.DAL;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class KeywordsDepartmentsController : Controller
    {
        private TicketContext db = new TicketContext();

        // GET: KeywordsDepartments
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Index()
        {
            var keywordsDepartments = db.KeywordsDepartments.Include(k => k.Department);
            return View(keywordsDepartments.ToList());
        }

        // GET: KeywordsDepartments/Details/5
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KeywordsDepartment keywordsDepartment = db.KeywordsDepartments.Find(id);
            if (keywordsDepartment == null)
            {
                return HttpNotFound();
            }
            return View(keywordsDepartment);
        }

        // GET: KeywordsDepartments/Create
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentId", "DepartmentName");
            return View();
        }

        // POST: KeywordsDepartments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Create([Bind(Include = "KeywordID,Keyword,DepartmentID")] KeywordsDepartment keywordsDepartment)
        {
            if (ModelState.IsValid)
            {
                db.KeywordsDepartments.Add(keywordsDepartment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentId", "DepartmentName", keywordsDepartment.DepartmentID);
            return View(keywordsDepartment);
        }

        // GET: KeywordsDepartments/Edit/5
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KeywordsDepartment keywordsDepartment = db.KeywordsDepartments.Find(id);
            if (keywordsDepartment == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentId", "DepartmentName", keywordsDepartment.DepartmentID);
            return View(keywordsDepartment);
        }

        // POST: KeywordsDepartments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Edit([Bind(Include = "KeywordID,Keyword,DepartmentID")] KeywordsDepartment keywordsDepartment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(keywordsDepartment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentId", "DepartmentName", keywordsDepartment.DepartmentID);
            return View(keywordsDepartment);
        }

        // GET: KeywordsDepartments/Delete/5
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KeywordsDepartment keywordsDepartment = db.KeywordsDepartments.Find(id);
            if (keywordsDepartment == null)
            {
                return HttpNotFound();
            }
            return View(keywordsDepartment);
        }

        // POST: KeywordsDepartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult DeleteConfirmed(int id)
        {
            KeywordsDepartment keywordsDepartment = db.KeywordsDepartments.Find(id);
            db.KeywordsDepartments.Remove(keywordsDepartment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TeaCat System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TeaCat System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Agent", "Index", "Agent")</li>
                    <li>@Html.ActionLink("Ticket", "Index", "Ticket")</li>
                    <li>@Html.ActionLink("Department", "Index", "Department")</li>
                    <li>@Html.ActionLink("Keywords", "Index", "KeywordsDepartments")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TeaCat System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>