Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication5.Models
{
    public class Ticket
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int TicketID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public TicketStatus Status { get; set; }
        public DateTime CreatedAt { get; set; }
        public int AgentID { get; set; }
        public int? DepartmentID { get; set; }
        public string RequesterID { get; set; }

        public enum TicketStatus
        {
            Open = 1,
            Solved = 2
        }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual Department Department { get; set; }
    }
}

Controllers/TicketController.cs
using PagedList;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication5.DAL;
using WebApplication5.Models;
using Microsoft.AspNet.Identity;

namespace WebApplication5.Controllers
{
    public class TicketController : Controller
    {
        private TicketContext db = new TicketContext();

        // GET: Ticket
        [Authorize(Roles = "TCAdmin,TCManager,TCAgent")] // AUTHORIZE ONLY USERS IN THE FOLLOWING ROLES - TCAdmin, TCAgent and TCManager
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            // TICKET SORTING
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "body_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "status_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            // SERACH FUNCTION
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            // SHOWING ONLY OPENED TICKETS
            var tickets = from s in db.Tickets where s.Status.ToString().Contains("Open")
                          select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                tickets = tickets.Where(s => s.Title.Contains(searchString)
                                        || s.Body.Contains(searchString)
                                        || s.Status.ToString().Contains(searchString)
                                        || s.TicketID.ToString().Contains(searchString)
                                        || s.CreatedAt.ToString().Contains(searchString)
                                        || s.Agent.FirstName.ToString().Contains(searchString)
                                        || s.Department.DepartmentName.ToString().Contains(searchString)
                                        );
            }
            // SORTING OPTIONS
            switch (sortOrder)
            {
                case "title_desc":
                    tickets = tickets.OrderByDescending(s => s.Title);
                    break;
                case "body_desc":
                    tickets = tickets.OrderBy(s => s.Body);
                    break;
                case "status_desc":
                    tickets = tickets.OrderByDescending(s => s.Status);
                    break;
                case "id_desc":
                    tickets = tickets.OrderBy(s => s.TicketID);
                    break;
                case "date_desc":
                    tickets = tickets.OrderByDescending(s => s.CreatedAt);
                    break;
                default:
                    tickets = tickets.OrderBy(s => s.TicketID);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(tickets.ToPagedList(pageNumber, pageSize));
        }

        // GET: Ticket/Details/5 - TICKET DETAILS
        [Authorize(Roles = "TCAdmin,TCManager,TCAgent")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET ALL TICKETS SUBMITTED BY LOGGED IN USER
        [Authorize]
        public ActionResult MyTickets()
        {
            string currentUserId = User.Identity.GetUserId();
            ViewBag.myTicketList = db.Tickets.Where(m => m.RequesterID.Contains(currentUserId)).ToList();
            var theResult = db.Tickets.Where(m => m.RequesterID.Contains(currentUserId)).ToList();
            return View(theResult);
        }

        // GET: Ticket/Create
        /*
         * WORKS IN THE FOLLOWING WAY:
         * PARTIAL USER DATA IS SAVED ON THE TICKET
         * WHEN THE TICKET IS SUBMITTED, SYSTEM SCANS THE TICKET FOR THE KEYWORDS AND KEEPS A SCORE FOR EACH KEYWORD FOUND AND DEPARTMENT
         * THE SCORE IS THEN EVALUATED AND THE DEPARTMENT WITH THE BEST SCORE IS SELECTED
         * ALL AGENTS FROM THE SELECTED DEPARTMENT ARE PULLED
         * ALL TICKETS ASSIGNED TO AGENTS ARE PULLED
         * THE TICKET NUMBER BETWEEN EACH AGENT IS EVALUATED
         * TICKET GOES TO AGENT WITH LEAST TICKETS IN THE DEPARTMENT
         * DB TABLES FOR TICKETS AND AGENTS ARE UPDATED TO REFLECT CHANGES
         */
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "TicketID,Title,Body,Status,CreatedAt,AgentID,DepartmentID")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                // ASSIGNMENT OPERATION
                int numberOdDepartments = this.db.Departments.Max(thedepartment => thedepartment.DepartmentID); // GET THE NUMBER OF DEPARTMENTS
                int[][] DepartmentIDandKeywordMatches = new int[numberOdDepartments][]; // CREATE A JAGGED ARRAY FOR EACH DEPARTMENT
                System.Diagnostics.Debug.WriteLine("There are " + numberOdDepartments + " departments.");
                int matchScore; // INSTANTIATE THE MATCH SCORE
                int matchDepartment = 1;
                int agentLeastTicketsID = 1;

                // CREATE A JAGGED ARRAY FOR EACH DEPARTMENT [DEPARTMENT ID][# OF MATCHES]
                for (int i=0; i< numberOdDepartments; i++)
                {
                    DepartmentIDandKeywordMatches[i] = new int[] { 0 };
                }

                string ticketTitleWord = ticket.Title.ToString(); // TAKE INPUT FROM TICKET TITLE
                string ticketBodyWord = ticket.Body.ToString(); // TAKE INPUT FROM TICKET BODY
                string titleAndBodyWord = ticketTitleWord + " " + ticketBodyWord; // COMBINE INTO 1 STRING
                string[] ticketWordList = titleAndBodyWord.Split(null); // ISOLATE EACH WORD

                foreach (var word in ticketWordList) // ITERATE THROUGH TICKET WORDS
                {
                    var result1 = db.KeywordsDepartments.Where(x => x.Keyword.Contains(word)).ToList(); // FETCH KEYWORDS
                    var result = result1.ToString();
                    foreach(var keyword in result1) // ITERATE THROUGH KEYWORDS
                    {
                        bool matches = word.Equals(keyword.Keyword.ToString(), StringComparison.OrdinalIgnoreCase); // COMPARE
                        if (matches) // IF THEY MATCH
                        {
                            System.Diagnostics.Debug.WriteLine("Match found.");
                            int targetDepartmentID = keyword.DepartmentID ; // GET DEPARTMENT INDEX FROM DB
                            int y = DepartmentIDandKeywordMatches[targetDepartmentID][0]; // GET DEPARTMENT ID FROM ARRAY
                            int z = y + 1; // INCREMENT SCORE FOR # OF MATCHES
                            DepartmentIDandKeywordMatches[targetDepartmentID][0] = z; // UPDATE THE SCORE

                            //int matchScore; // INSTANTIATE THE MATCH SCORE
                            //int matchDepartment;
                            for (int n = 0; n < DepartmentIDandKeywordMatches.Length; n++) // ITERATE THROUGH ARRAY
                            {
                                for (int k = 0; k < DepartmentIDandKeywordMatches[n].Length; k++)
                                {
                                    matchScore = DepartmentIDandKeywordMatches[0][0]; // MATCH SCORE IS THE 1ST SCORE IN ARRAY
                                    if(DepartmentIDandKeywordMatches[n][k] > matchScore) // IF THE BIGGER SCORE IS FOUND
                                    {
                                        matchScore = DepartmentIDandKeywordMatches[n][k]; // MATCH SCORE IS THE BIGGER SCORE
                                        matchDepartment = n; // DEPARTMENT ID WITH MOST MATCHES
                                        System.Diagnostics.Debug.WriteLine("Score: " + matchScore);
                                    }
                                }
                            }
                        }
                    }
                }
   
                var agentsResult = db.Agents.Where(m => m.DepartmentID.Equals(matchDepartment)).ToList(); // FETCH AGENTS FROM TARGET DEPARTMENT
                bool firstAgent = true; // BOOL TO TAKE THE VALUE FROM 1ST AGENT AS PARAM
                int agentLeastTickets = 500; // INSTANTIATE
                foreach(var agent in agentsResult)
                {
                    if (firstAgent) // SET 1ST AFENT AS COMPARISON
                    {
                        agentLeastTickets = agent.TicketsAssigned;
                        agentLeastTicketsID = agent.AgentID;
                        firstAgent = false; // MAKE THIS PART UNAVAILABLE FOR THE REST
                    }
                    if (agent.TicketsAssigned < agentLeastTickets) // IF THERE'S AN AGENT WITH LESS TICKETS THAN 1ST AGENT
                    {

Views/Ticket/Create.cshtml
@model WebApplication5.Models.Ticket

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Ticket</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Body, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Ticket/Delete.cshtml
@model WebApplication5.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete ticket</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Ticket/Details.cshtml
@model WebApplication5.Models.Ticket

@{
    ViewBag.Title = "Details";
}

<h2>Ticket Details</h2>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agent.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Agent.FirstName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TicketID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Ticket/Edit.cshtml
@model WebApplication5.Models.Ticket

@{
    ViewBag.Title = "Edit";
}

<h2>Edit ticket</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Ticket</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TicketID)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Body, htmlAttributes: new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgentID, "Asignee", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("AgentID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AgentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control"  })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Ticket/Index.cshtml
@model PagedList.IPagedList<WebApplication5.Models.Ticket>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Tickets";
}

<h2>List of tickets</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Ticket", FormMethod.Get))
{
    <p>
        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" class="btn btn-default" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Ticket ID", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Created At", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Assignee", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Department", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>






    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TicketID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedAt)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Agent.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Agent.Department.DepartmentName)
    </td>

    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.TicketID }) |
        @Html.ActionLink("Details", "Details", new { id = item.TicketID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.TicketID })
    </td>
</tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Views/Ticket/MyTickets.cshtml
@model System.Collections.Generic.List<WebApplication5.Models.Ticket>

@{
    ViewBag.Title = "My Tickets";
}

<br />
<h2>Tickets submitted</h2>
<br />

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Title", null, new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Agent", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Created", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Body", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var element in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(m => element.Title)
            </td>
            <td>
                @Html.DisplayFor(m => element.Status)
            </td>
            <td>
                @Html.DisplayFor(m => element.Agent.FirstName)
            </td>
            <td>
                @Html.DisplayFor(m => element.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(m => element.Body)
            </td>
        </tr>
    }

</table>