Models/Agent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication5.Models
{
    public class Agent
    {
        public int AgentID { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public int DepartmentID { get; set; }
        public string Role { get; set; }
        public int TicketsAssigned { get; set; }
        public int TicketsSolved { get; set; }
        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public virtual ApplicationUser User { get; set; }
        public virtual Department Department { get; set; }

    }
}

Controllers/AgentController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication5.DAL;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class AgentController : Controller
    {
        private TicketContext db = new TicketContext();
        private ApplicationDbContext dbc = new ApplicationDbContext();


        // GET: Agent
        [Authorize(Roles = "TCAdmin")]
        //[Authorize(Roles = "TCManager")]
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "surn_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "email_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "dept_desc" : "";
            // SEARCH FUNCTION
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var agents = from s in db.Agents
                         select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                agents = agents.Where(s => s.Surname.Contains(searchString)
                                        || s.FirstName.Contains(searchString)
                                        || s.Email.Contains(searchString)
                                        || s.Department.DepartmentName.Contains(searchString)
                                        );
            }

            // SORTING AGENTS BY PARAMETERS
            switch (sortOrder)
            {
                // SORT ALPHABETICALLY BY SURNAME
                case "surn_desc":
                    agents = agents.OrderByDescending(s => s.Surname);
                    break;
                // SORT ALPHABETICALLY BY NAME
                case "name_desc":
                    agents = agents.OrderBy(s => s.FirstName);
                    break;
                // SORT ALPHABETICALLY BY EMAIL
                case "email_desc":
                    agents = agents.OrderByDescending(s => s.Email);
                    break;
                // SORT ALPHABETICALLY BY DEPARTMENT NAME
                case "dept_desc":
                    agents = agents.OrderBy(s => s.Department.DepartmentName);
                    break;
                // DEFAULT  - SORT ALPHABETICALLY BY SURNAME
                default:
                    agents = agents.OrderBy(s => s.Surname);
                    break;
            }
            // LIMIT RESULTS TO 10 PER PAGE
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(agents.ToPagedList(pageNumber, pageSize));
        }



        // GET: Agent/Details/5
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = db.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // GET: Agent/Create 
        [Authorize(Roles = "TCAdmin")]
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepartmentName"); // FETCH DEPARTMENTS
            ViewBag.UserId = new SelectList(dbc.Users, "Id", "UserName"); // FETCH USERNAME
            ViewBag.Email = new SelectList(dbc.Users, "Email", "Email"); // FETCH EMAIL
            ViewBag.Role = new SelectList(dbc.Roles, "Id", "Name"); // FETCH ROLES
            return View();
        }

        // POST: Agent/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AgentID,Surname,FirstName,Email,DepartmentID,Id,UserName,Email,UserId,Id,Role")] Agent agent)
        {
            if (ModelState.IsValid)
            {
                var oldnextAgentId1 = this.db.Agents.OrderByDescending(theagent => theagent.AgentID).First(); // ASSIGN ID TO PREVENT CONCURENCY
                int oldnextAgentId = int.Parse(oldnextAgentId1.AgentID.ToString());
                var newAgentId = oldnextAgentId + 1; // ASSIGN ID TO PREVENT CONCURENCY
                System.Diagnostics.Debug.WriteLine("Agent ID is " + newAgentId);
                System.Diagnostics.Debug.WriteLine("User ID is " + agent.UserId.ToString());
                agent.AgentID = newAgentId; // ASSIGN ID TO PREVENT CONCURENCY
                db.Agents.Add(agent); // CREATE AGENT
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var ue = ViewBag.Email = new SelectList(dbc.Users, "Email", "Email", agent.Email); // FETCH EMAIL
            var uid = ViewBag.UserId = new SelectList(dbc.Users, "Id", "UserName", agent.UserId); // FETCH USER ID
            var ur = ViewBag.Role= new SelectList(dbc.Roles, "Id", "Name", agent.Role);  // FETCH ROLES
            var did = ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID",null , agent.DepartmentID); // FETCH DEPARTMENTS

            var userStore = new UserStore<ApplicationUser>(dbc);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(agent.UserId, agent.Role);
            db.SaveChanges();
            dbc.SaveChanges();
            return View(agent);
        }

        // GET: Agent/Edit/5
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = db.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            ViewBag.Role = new SelectList(dbc.Roles, "Id", "Name", agent.Role);  // FETCH ROLES
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepartmentName");
            return View(agent);
        }

        // POST: Agent/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AgentID,Surname,FirstName,Email,DepartmentID")] Agent agent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepartmentName", agent.DepartmentID);

            var uid = ViewBag.UserId = new SelectList(dbc.Users, "Id", "UserName", agent.UserId); // FETCH USER ID
            var ur = new SelectList(dbc.Roles, "Id", "Name", agent.Role);  // FETCH ROLES
            ViewBag.Role = ur;

            var userStore = new UserStore<ApplicationUser>(dbc);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(agent.UserId, agent.Role);


            return View(agent);
        }

        // GET: Agent/Delete/5
        [Authorize(Roles = "TCAdmin,TCManager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = db.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // POST: Agent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agent agent = db.Agents.Find(id);
            db.Agents.Remove(agent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Agent/Create.cshtml
@model WebApplication5.Models.Agent

@{
    ViewBag.Title = "Create";
}

<h2>Create a new agent</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Agent</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Surname, "Surname", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, "First name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.User.Id, "Username", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.User.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.User.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Email", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.User.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Role, "Role", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Role", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Agent/Delete.cshtml
@model WebApplication5.Models.Agent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete agent</h2>

<h3>Are you sure you want to delete this agent?</h3>
<div>
    <h4>Agent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Agent/Details.cshtml
@model WebApplication5.Models.Agent

@{
    ViewBag.Title = "Details";
}

<h2>Details about agent</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.FirstName, "First Name")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>
        <br />
        <br />

        <dt>
            @Html.DisplayNameFor(model => model.Assignments)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Tickets assigned</th>
                    <th>Tickets solved</th>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.TicketsAssigned)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.TicketsSolved)
                    </td>
                </tr>

            </table>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AgentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Agent/Edit.cshtml
@model WebApplication5.Models.Agent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit agent details</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Agent</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.AgentID)

    <!-- FIRST NAME -->
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- SURNAME -->
    <div class="form-group">
        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- EMAIL -->
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- DEPARTMENT -->
    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "DepartmentID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- ROLE -->
    <div class="form-group">
        @Html.LabelFor(model => model.Role, "Role", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Role", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Agent/Index.cshtml
@model PagedList.IPagedList<WebApplication5.Models.Agent>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Agents";
}

<h2>List of agents</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Agent", FormMethod.Get))
{
    <p>
        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" class="btn btn-default" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Surname", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Department", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.DepartmentName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.AgentID }) |
                @Html.ActionLink("Details", "Details", new { id = item.AgentID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.AgentID })
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))